# Generated by Django 5.0.6 on 2026-09-06 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_type', models.CharField(choices=[('night_owl', '🌙 Night Owl'), ('early_bird', '☀️ Early Bird / Day Bird')], max_length=12)),
                ('sleep_time', models.TimeField(help_text='Typical time you fall asleep')),
                ('wake_time', models.TimeField(help_text='Typical time you wake up')),
                ('quiet_hours', models.CharField(blank=True, help_text='e.g. 11 PM – 7 AM', max_length=60)),
                ('light_preference', models.CharField(choices=[('off', 'Need lights OFF while sleeping'), ('dim', 'Prefer dim / night light'), ('dont_mind', "Don't mind lights"), ('on_study', 'Prefer lights ON while studying')], max_length=12)),
                ('study_habit', models.CharField(choices=[('room', 'Study mostly in the room'), ('library', 'Study mostly in library'), ('occasional', 'Study occasionally'), ('late_night', 'Study late at night'), ('early_morning', 'Study early morning')], max_length=14)),
                ('noise_preference', models.CharField(choices=[('quiet', 'Need a very quiet room'), ('moderate', 'Prefer moderate noise'), ('dont_mind', "Don't mind noise")], max_length=12)),
                ('cleanliness', models.CharField(choices=[('very', 'Very clean'), ('moderate', 'Moderately clean'), ('relaxed', 'Relaxed about cleanliness')], max_length=10)),
                ('social_level', models.CharField(choices=[('very', 'Very social'), ('moderate', 'Moderately social'), ('private', 'Quiet / private')], max_length=10)),
                ('visitor_preference', models.CharField(choices=[('none', 'Prefer no visitors'), ('occasional', 'Occasional visitors are okay'), ('okay', 'Visitors are okay')], max_length=12)),
                ('preferred_room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double sharing'), ('triple', 'Triple sharing'), ('any', 'Any')], default='any', max_length=10)),
                ('preferred_room_location', models.CharField(choices=[('corner', 'Corner room'), ('middle', 'Middle of corridor'), ('near_stairs', 'Near stairs / exit'), ('any', 'Any')], default='any', max_length=12)),
                ('ok_with_other_branch', models.BooleanField(default=True)),
                ('ok_with_other_year', models.BooleanField(default=True)),
                ('eating_in_room', models.BooleanField(default=False)),
                ('cooking_in_room', models.BooleanField(default=False)),
                ('fragrance_sensitive', models.BooleanField(default=False)),
                ('music_video', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(max_length=120)),
                ('floor', models.SmallIntegerField()),
                ('room_number', models.CharField(max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('available_beds', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'ordering': ['hostel', 'floor', 'room_number'],
                'unique_together': {('hostel', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='RoommateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
